//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Mx.TlsEntity.Dao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TlsEntityDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TlsEntityDaoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Mx.TlsEntity.Dao.TlsEntityDaoResources", typeof(TlsEntityDaoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `mx`.`TlsEntity`
        ///WHERE `TlsEntity`.`hostname` = @hostname;
        ///    .
        /// </summary>
        public static string DeleteTlsEntity {
            get {
                return ResourceManager.GetString("DeleteTlsEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT r1.domain, r2.hostname, t.state FROM mx.MxRecord r1
        ///join mx.MxRecord r2 on r1.domain = r2.domain
        ///join mx.TlsEntity t on t.hostname = r2.hostname
        ///where r1.hostname = @hostname
        ///    .
        /// </summary>
        public static string GetDomainMxHosts {
            get {
                return ResourceManager.GetString("GetDomainMxHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT `TlsEntity`.`state`
        ///FROM `mx`.`TlsEntity`
        ///WHERE `TlsEntity`.`hostname` = @hostname;
        ///    .
        /// </summary>
        public static string GetTlsEntity {
            get {
                return ResourceManager.GetString("GetTlsEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `mx`.`TlsEntity`
        ///(`hostname`,
        ///`state`)
        ///VALUES
        ///(@hostname,
        ///@state)        
        ///ON DUPLICATE KEY UPDATE
        ///`hostname`=@hostname,
        ///`state`=@state;
        ///    .
        /// </summary>
        public static string SaveTlsEntity {
            get {
                return ResourceManager.GetString("SaveTlsEntity", resourceCulture);
            }
        }
    }
}
