//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Mx.TlsEntity.Dao {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TlsEntityDaoResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TlsEntityDaoResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Mx.TlsEntity.Dao.TlsEntityDaoResources", typeof(TlsEntityDaoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DeleteTlsEntity {
            get {
                return ResourceManager.GetString("DeleteTlsEntity", resourceCulture);
            }
        }
        
        public static string GetTlsEntity {
            get {
                return ResourceManager.GetString("GetTlsEntity", resourceCulture);
            }
        }
        
        public static string SaveTlsEntity {
            get {
                return ResourceManager.GetString("SaveTlsEntity", resourceCulture);
            }
        }
        
        public static string GetDomainMxHosts {
            get {
                return ResourceManager.GetString("GetDomainMxHosts", resourceCulture);
            }
        }
        
        public static string GetDomainsFromMxHost {
            get {
                return ResourceManager.GetString("GetDomainsFromMxHost", resourceCulture);
            }
        }
        
        public static string GetHostsStates {
            get {
                return ResourceManager.GetString("GetHostsStates", resourceCulture);
            }
        }
    }
}
