//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Mx.TlsEvaluator.Rules.CertificateEvaluation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CertificateEvaluatorErrors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificateEvaluatorErrors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Mx.TlsEvaluator.Rules.CertificateEvaluation.CertificateEvaluatorErrors", typeof(CertificateEvaluatorErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AllCertificatesShouldBeInOrder {
            get {
                return ResourceManager.GetString("AllCertificatesShouldBeInOrder", resourceCulture);
            }
        }
        
        public static string AllCertificatesShouldBePresent {
            get {
                return ResourceManager.GetString("AllCertificatesShouldBePresent", resourceCulture);
            }
        }
        
        public static string AllCertificatesShouldHaveStrongKey {
            get {
                return ResourceManager.GetString("AllCertificatesShouldHaveStrongKey", resourceCulture);
            }
        }
        
        public static string AllCertificatesSignaturesShouldBeValid {
            get {
                return ResourceManager.GetString("AllCertificatesSignaturesShouldBeValid", resourceCulture);
            }
        }
        
        public static string CertificateExpiryShouldBeInDateExpired {
            get {
                return ResourceManager.GetString("CertificateExpiryShouldBeInDateExpired", resourceCulture);
            }
        }
        
        public static string CertificateExpiryShouldBeInDateExpiringSoon {
            get {
                return ResourceManager.GetString("CertificateExpiryShouldBeInDateExpiringSoon", resourceCulture);
            }
        }
        
        public static string CertificateShouldMatchHostName {
            get {
                return ResourceManager.GetString("CertificateShouldMatchHostName", resourceCulture);
            }
        }
        
        public static string HostShouldHaveCertificates {
            get {
                return ResourceManager.GetString("HostShouldHaveCertificates", resourceCulture);
            }
        }
        
        public static string NonRootCertificatesShouldNotAppearOnRevocationListsError {
            get {
                return ResourceManager.GetString("NonRootCertificatesShouldNotAppearOnRevocationListsError", resourceCulture);
            }
        }
        
        public static string NonRootCertificatesShouldNotAppearOnRevocationListsRevoked {
            get {
                return ResourceManager.GetString("NonRootCertificatesShouldNotAppearOnRevocationListsRevoked", resourceCulture);
            }
        }
        
        public static string RootCertificateShouldBeTrusted {
            get {
                return ResourceManager.GetString("RootCertificateShouldBeTrusted", resourceCulture);
            }
        }
    }
}
